"""Tests for tools.reindex — unified session + concept index entry point.

Per references/tools-spec.md §6.1. reindex.py is a thin CLI wrapper that
delegates to cortex helpers (session_index.rebuild_index and
concept.rebuild_concept_index) — the behavioural contracts here focus on
the CLI: flag parsing, exit codes, output files, and idempotence.
"""

from __future__ import annotations

from datetime import date, datetime
from pathlib import Path

from tools.lib.cortex.concept import write_concept
from tools.lib.cortex.session_index import session_summary_to_markdown
from tools.lib.second_brain import (
    Concept,
    ConceptProvenance,
    SessionSummary,
)
from tools.reindex import main

# ─── Fixtures ───────────────────────────────────────────────────────────────


def _make_summary(
    session_id: str = "claude-20260421-1430",
    date_val: date = date(2026, 4, 21),
) -> SessionSummary:
    return SessionSummary(
        session_id=session_id,
        date=date_val,
        started_at=datetime.combine(date_val, datetime.min.time()).replace(hour=14),
        ended_at=datetime.combine(date_val, datetime.min.time()).replace(
            hour=14, minute=30
        ),
        duration_minutes=30,
        platform="claude",
        theme="zh-classical",
        project="life-os",
        workflow="full_deliberation",
        subject="test",
        overall_score=8.5,
        veto_count=0,
        council_triggered=False,
        compliance_violations=0,
        body="body",
        keywords=["k1", "k2"],
    )


def _write_session(root: Path, session_id: str, date_val: date) -> Path:
    sessions_dir = root / "_meta" / "sessions"
    sessions_dir.mkdir(parents=True, exist_ok=True)
    s = _make_summary(session_id=session_id, date_val=date_val)
    path = sessions_dir / f"{session_id}.md"
    path.write_text(session_summary_to_markdown(s), encoding="utf-8")
    return path


def _make_concept(concept_id: str = "strategy", domain: str = "professional") -> Concept:
    return Concept(
        concept_id=concept_id,
        canonical_name=concept_id.replace("-", " ").title(),
        domain=domain,
        status="confirmed",
        permanence="skill",
        activation_count=5,
        last_activated=datetime(2026, 4, 20, 12, 0),
        created=datetime(2026, 1, 1, 12, 0),
        body="A test concept.",
        aliases=[],
        outgoing_edges=[],
        provenance=ConceptProvenance(source_sessions=["claude-20260421-1430"]),
    )


# ─── --sessions flag ─────────────────────────────────────────────────────────


class TestSessionsOnly:
    def test_writes_session_index_only(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        rc = main(["--sessions", "--root", str(tmp_path)])
        assert rc == 0
        idx = tmp_path / "_meta" / "sessions" / "INDEX.md"
        assert idx.exists()
        # Concepts INDEX not written because --sessions only
        assert not (tmp_path / "_meta" / "concepts" / "INDEX.md").exists()

    def test_index_header_has_generator_marker(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        rc = main(["--sessions", "--root", str(tmp_path)])
        assert rc == 0
        content = (tmp_path / "_meta" / "sessions" / "INDEX.md").read_text(
            encoding="utf-8"
        )
        assert "generated by tools/reindex.py" in content

    def test_empty_sessions_dir_exits_zero(self, tmp_path: Path):
        (tmp_path / "_meta" / "sessions").mkdir(parents=True)
        rc = main(["--sessions", "--root", str(tmp_path)])
        assert rc == 0


# ─── --concepts flag ─────────────────────────────────────────────────────────


class TestConceptsOnly:
    def test_writes_concept_index_only(self, tmp_path: Path):
        concepts_root = tmp_path / "_meta" / "concepts"
        concepts_root.mkdir(parents=True)
        write_concept(_make_concept(), concepts_root)
        rc = main(["--concepts", "--root", str(tmp_path)])
        assert rc == 0
        idx = concepts_root / "INDEX.md"
        assert idx.exists()
        # Sessions INDEX not written because --concepts only
        assert not (tmp_path / "_meta" / "sessions" / "INDEX.md").exists()

    def test_concept_header_has_generator_marker(self, tmp_path: Path):
        concepts_root = tmp_path / "_meta" / "concepts"
        concepts_root.mkdir(parents=True)
        write_concept(_make_concept(), concepts_root)
        rc = main(["--concepts", "--root", str(tmp_path)])
        assert rc == 0
        content = (concepts_root / "INDEX.md").read_text(encoding="utf-8")
        assert "generated by tools/reindex.py" in content

    def test_empty_concepts_dir_exits_zero(self, tmp_path: Path):
        (tmp_path / "_meta" / "concepts").mkdir(parents=True)
        rc = main(["--concepts", "--root", str(tmp_path)])
        assert rc == 0


# ─── --all flag (default) ────────────────────────────────────────────────────


class TestAllFlag:
    def test_all_writes_both_indices(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        concepts_root = tmp_path / "_meta" / "concepts"
        concepts_root.mkdir(parents=True)
        write_concept(_make_concept(), concepts_root)

        rc = main(["--all", "--root", str(tmp_path)])
        assert rc == 0
        assert (tmp_path / "_meta" / "sessions" / "INDEX.md").exists()
        assert (tmp_path / "_meta" / "concepts" / "INDEX.md").exists()

    def test_no_flag_defaults_to_all(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        concepts_root = tmp_path / "_meta" / "concepts"
        concepts_root.mkdir(parents=True)
        write_concept(_make_concept(), concepts_root)

        rc = main(["--root", str(tmp_path)])
        assert rc == 0
        assert (tmp_path / "_meta" / "sessions" / "INDEX.md").exists()
        assert (tmp_path / "_meta" / "concepts" / "INDEX.md").exists()


# ─── Idempotence ─────────────────────────────────────────────────────────────


class TestIdempotence:
    def test_sessions_idempotent(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        main(["--sessions", "--root", str(tmp_path)])
        first = (tmp_path / "_meta" / "sessions" / "INDEX.md").read_text(
            encoding="utf-8"
        )
        main(["--sessions", "--root", str(tmp_path)])
        second = (tmp_path / "_meta" / "sessions" / "INDEX.md").read_text(
            encoding="utf-8"
        )
        assert first == second

    def test_all_idempotent(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        concepts_root = tmp_path / "_meta" / "concepts"
        concepts_root.mkdir(parents=True)
        write_concept(_make_concept(), concepts_root)

        main(["--all", "--root", str(tmp_path)])
        s1 = (tmp_path / "_meta" / "sessions" / "INDEX.md").read_text(encoding="utf-8")
        c1 = (tmp_path / "_meta" / "concepts" / "INDEX.md").read_text(encoding="utf-8")

        main(["--all", "--root", str(tmp_path)])
        s2 = (tmp_path / "_meta" / "sessions" / "INDEX.md").read_text(encoding="utf-8")
        c2 = (tmp_path / "_meta" / "concepts" / "INDEX.md").read_text(encoding="utf-8")

        assert s1 == s2
        assert c1 == c2


# ─── Error handling ──────────────────────────────────────────────────────────


class TestErrorHandling:
    def test_malformed_frontmatter_skipped_not_fatal(self, tmp_path: Path):
        sessions_dir = tmp_path / "_meta" / "sessions"
        sessions_dir.mkdir(parents=True)
        # A well-formed entry
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        # A file with malformed YAML — should be skipped, not crash the tool
        (sessions_dir / "bad.md").write_text(
            "---\nnot: [valid: yaml\n---\nbody\n", encoding="utf-8"
        )
        rc = main(["--sessions", "--root", str(tmp_path)])
        assert rc == 0
        content = (sessions_dir / "INDEX.md").read_text(encoding="utf-8")
        # The good one is indexed
        assert "claude-20260421-1430" in content

    def test_verbose_accepted(self, tmp_path: Path):
        _write_session(tmp_path, "claude-20260421-1430", date(2026, 4, 21))
        rc = main(["--sessions", "--verbose", "--root", str(tmp_path)])
        assert rc == 0


# ─── Flag exclusivity ────────────────────────────────────────────────────────


class TestFlagExclusivity:
    def test_sessions_and_concepts_cannot_both_be_passed(self, tmp_path: Path):
        import pytest

        with pytest.raises(SystemExit):
            main(["--sessions", "--concepts", "--root", str(tmp_path)])
