#!/usr/bin/env bash
# Register Life OS agent wrappers for Claude Code's native Task() discovery.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ]; then
  SKILL_ROOT="$CLAUDE_PLUGIN_ROOT"
elif [ -f "$SCRIPT_ROOT/pro/agents/router.md" ]; then
  SKILL_ROOT="$SCRIPT_ROOT"
elif [ -d "$HOME/.claude/skills/life_OS" ]; then
  SKILL_ROOT="$HOME/.claude/skills/life_OS"
elif [ -d "$HOME/.claude/skills/life-os" ]; then
  SKILL_ROOT="$HOME/.claude/skills/life-os"
elif [ -f "$(pwd)/pro/agents/router.md" ]; then
  SKILL_ROOT="$(pwd)"
else
  echo "ERROR: Cannot locate life_OS skill root" >&2
  exit 1
fi

AGENTS_SOURCE_DIR="$SKILL_ROOT/pro/agents"
AGENTS_DIR="$HOME/.claude/agents"

if [ ! -d "$AGENTS_SOURCE_DIR" ]; then
  echo "ERROR: Cannot find agent definitions: $AGENTS_SOURCE_DIR" >&2
  exit 1
fi

mkdir -p "$AGENTS_DIR"

REGISTERED=0
SKIPPED=0

for agent_file in "$AGENTS_SOURCE_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  base="$(basename "$agent_file" .md)"

  if grep -qE '^type:[[:space:]]*router-internal-template' "$agent_file"; then
    echo "skip $base (ROUTER-internal template, not Task-spawnable)"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  wrapper="$AGENTS_DIR/lifeos-${base}.md"
  tmp="${wrapper}.tmp"

  awk -v name="lifeos-${base}" '
    BEGIN { in_fm=0; fm_done=0 }
    /^---$/ {
      if (!in_fm && !fm_done) { in_fm=1; print; next }
      if (in_fm) { in_fm=0; fm_done=1; print; exit }
    }
    in_fm && /^name:/ { print "name: " name; next }
    in_fm { print }
  ' "$agent_file" > "$tmp"

  cat >> "$tmp" <<EOF

# Life OS - $base (auto-generated wrapper)

You are the Life OS \`$base\` agent. Your authoritative definition lives at:

    $agent_file

Read that file first, then execute its instructions.

Path conventions:
- \`pro/*\`, \`themes/*\`, \`references/*\`, \`docs/*\` -> under \`$SKILL_ROOT/\`
- \`_meta/\`, \`projects/\`, \`areas/\`, \`wiki/\`, \`SOUL.md\` -> under the user's current working directory

This wrapper was generated by \`scripts/register-claude-agents.sh\`. Do not edit
it by hand; edit \`pro/agents/${base}.md\` and re-run the register script.
EOF

  mv "$tmp" "$wrapper"
  REGISTERED=$((REGISTERED + 1))
done

echo "Registered $REGISTERED lifeos-* agents under $AGENTS_DIR (skipped $SKIPPED templates)"
