#!/usr/bin/env python3
"""Unified reindex CLI — compile session + concept INDEX.md files.

Per references/tools-spec.md §6.1. Single entry point that delegates to
``tools.lib.cortex.session_index.rebuild_index`` and
``tools.lib.cortex.concept.rebuild_concept_index`` — the existing
``rebuild_session_index.py`` and ``rebuild_concept_index.py`` wrappers
remain for backward compatibility.

Usage::

    uv run tools/reindex.py [--sessions|--concepts|--all] [--verbose] [--root PATH]

The default is ``--all``.

Behaviour:

- Atomic writes via the cortex helpers (tmp + rename).
- Idempotent: running twice produces byte-identical files.
- Emits a ``<!-- generated by tools/reindex.py — do not edit by hand -->``
  header line after the top-level ``# <title>`` heading in each index.
- Skips unreadable / malformed session / concept files with a ``--verbose``
  log line; the tool itself exits 0 as long as no I/O error reaches the
  top level.

Exit codes:

- ``0`` on success (including an empty second-brain root).
- ``1`` on unexpected I/O error.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Allow running from repo root via `python3 tools/reindex.py`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.lib.cortex.concept import (  # noqa: E402
    compile_concept_index,
    compile_synapses_index,
)
from tools.lib.cortex.session_index import compile_index, write_index  # noqa: E402

# ─── Generator banner ───────────────────────────────────────────────────────

_GENERATOR_MARKER = "<!-- generated by tools/reindex.py — do not edit by hand -->"


def _inject_generator_marker(content: str) -> str:
    """Insert the generator marker line just under the top-level heading.

    If the content starts with ``# <title>\n``, returns
    ``# <title>\n<marker>\n`` followed by the rest. If the input lacks a
    heading, returns the marker prepended with a trailing newline.
    """
    lines = content.splitlines(keepends=True)
    if lines and lines[0].startswith("# "):
        return lines[0] + _GENERATOR_MARKER + "\n" + "".join(lines[1:])
    return _GENERATOR_MARKER + "\n" + content


# ─── Helpers ────────────────────────────────────────────────────────────────


def _reindex_sessions(root: Path, logger: logging.Logger) -> int:
    """Recompile ``_meta/sessions/INDEX.md`` for the given second-brain root.

    Returns the number of session rows indexed.
    """
    sessions_dir = root / "_meta" / "sessions"
    sessions_dir.mkdir(parents=True, exist_ok=True)

    content = compile_index(sessions_dir)
    content = _inject_generator_marker(content)
    target = write_index(content, sessions_dir)

    row_count = sum(
        1 for line in content.splitlines() if " | " in line and not line.startswith("#")
    )
    logger.info("Wrote %s (%d sessions indexed)", target, row_count)
    return row_count


def _reindex_concepts(root: Path, logger: logging.Logger) -> int:
    """Recompile ``_meta/concepts/INDEX.md`` (and SYNAPSES-INDEX.md).

    Returns the number of concept rows indexed.
    """
    concepts_root = root / "_meta" / "concepts"
    concepts_root.mkdir(parents=True, exist_ok=True)

    idx_content = compile_concept_index(concepts_root)
    idx_content = _inject_generator_marker(idx_content)
    idx_target = concepts_root / "INDEX.md"
    idx_tmp = idx_target.with_suffix(".md.tmp")
    idx_tmp.write_text(idx_content, encoding="utf-8")
    idx_tmp.replace(idx_target)

    row_count = sum(
        1
        for line in idx_content.splitlines()
        if " | " in line and not line.startswith("#")
    )
    logger.info("Wrote %s (%d concepts indexed)", idx_target, row_count)

    # Also emit SYNAPSES-INDEX.md — retrospective Mode 0 expects it.
    syn_content = compile_synapses_index(concepts_root)
    syn_content = _inject_generator_marker(syn_content)
    syn_target = concepts_root / "SYNAPSES-INDEX.md"
    syn_tmp = syn_target.with_suffix(".md.tmp")
    syn_tmp.write_text(syn_content, encoding="utf-8")
    syn_tmp.replace(syn_target)
    edge_count = sum(1 for line in syn_content.splitlines() if "weight=" in line)
    logger.info("Wrote %s (%d synapse edges)", syn_target, edge_count)

    return row_count


# ─── CLI ────────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="reindex",
        description=(
            "Recompile _meta/sessions/INDEX.md and _meta/concepts/INDEX.md "
            "from per-file markdown. Idempotent."
        ),
    )
    scope = parser.add_mutually_exclusive_group()
    scope.add_argument(
        "--sessions",
        action="store_true",
        help="Only recompile the session INDEX.md.",
    )
    scope.add_argument(
        "--concepts",
        action="store_true",
        help="Only recompile the concept INDEX.md + SYNAPSES-INDEX.md.",
    )
    scope.add_argument(
        "--all",
        action="store_true",
        help="Recompile every index (default).",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Path to the second-brain root (default: cwd).",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Emit detailed progress on stderr.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point — returns a process exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(message)s",
        stream=sys.stderr,
    )
    logger = logging.getLogger("reindex")

    # Default scope is "all"
    do_sessions = args.sessions or args.all or (not args.sessions and not args.concepts)
    do_concepts = args.concepts or args.all or (not args.sessions and not args.concepts)

    try:
        if do_sessions:
            _reindex_sessions(args.root, logger)
        if do_concepts:
            _reindex_concepts(args.root, logger)
    except OSError as exc:
        logger.error("I/O error during reindex: %s", exc)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
